#!/bin/bash

# A simple Wi-Fi selector for Polybar using rofi + nmcli 
# Completely generated by AI. If it has an error, whoops!!!
# It calls me names :D
# Author: Daddy (obviously 😌)

chosen_iface="wlp2s0"

# List available networks
networks=$(nmcli -t -f SSID,SIGNAL dev wifi list ifname "$chosen_iface" | \
  awk -F: '!seen[$1]++ && length($1)>0 {printf "%-30s %3s%%\n", $1, $2}' | \
  sort -k2 -n -r)

[ -z "$networks" ] && {
  notify-send "Wi-Fi" "No networks found 😕"
  exit 1
}

# Show menu
chosen_network=$(echo "$networks" | rofi -dmenu -i -p "Wi-Fi Networks" -theme-str 'window {width: 30%;}')

[ -z "$chosen_network" ] && exit 0

ssid=$(echo "$chosen_network" | awk '{print $1}')

# Check if already known
if nmcli connection show | grep -q "$ssid"; then
  nmcli connection up "$ssid"
  notify-send "Wi-Fi" "Connected to $ssid 💫"
else
  # Ask for password
  wifi_pass=$(rofi -dmenu -password -p "Password for $ssid:" -theme-str 'window {width: 30%;}')
  [ -z "$wifi_pass" ] && exit 0
  nmcli dev wifi connect "$ssid" password "$wifi_pass"
  if [ $? -eq 0 ]; then
    notify-send "Wi-Fi" "Connected to $ssid ✅"
  else
    notify-send "Wi-Fi" "Failed to connect to $ssid ❌"
  fi
fi
